const mongoose = require('mongoose');

const platformInvoiceSchema = new mongoose.Schema({
  invoiceNumber: { type: String, required: true, unique: true, trim: true },
  tenantId: { type: mongoose.Schema.Types.ObjectId, ref: 'Tenant', required: true, index: true },
  planId: { type: mongoose.Schema.Types.ObjectId, ref: 'SubscriptionPlan' },

  amount: { type: Number, required: true },
  tax: { type: Number, default: 0 },
  discount: { type: Number, default: 0 },
  totalAmount: { type: Number, required: true },
  currency: { type: String, default: 'INR' },

  billingPeriod: {
    start: { type: Date },
    end: { type: Date }
  },

  status: {
    type: String,
    enum: ['draft', 'sent', 'paid', 'overdue', 'cancelled', 'refunded', 'partially_refunded'],
    default: 'draft',
    index: true
  },

  dueDate: { type: Date },
  paidAt: { type: Date },

  // Payment details
  paymentMethod: { type: String, enum: ['razorpay', 'stripe', 'bank_transfer', 'cash', 'cheque', 'upi', 'other'], default: null },
  transactionId: { type: String, trim: true },
  paymentReference: { type: String, trim: true },
  razorpayOrderId: { type: String },
  razorpayPaymentId: { type: String },

  // Refund
  refundAmount: { type: Number, default: 0 },
  refundReason: { type: String, trim: true },
  refundedAt: { type: Date },

  notes: { type: String, trim: true },
  isAutoGenerated: { type: Boolean, default: true }
}, { timestamps: true });

platformInvoiceSchema.index({ tenantId: 1, status: 1 });
platformInvoiceSchema.index({ dueDate: 1, status: 1 });
platformInvoiceSchema.index({ createdAt: -1 });

// Auto-generate invoice number
platformInvoiceSchema.pre('save', async function (next) {
  if (this.isNew && !this.invoiceNumber) {
    const count = await this.constructor.countDocuments();
    const date = new Date();
    this.invoiceNumber = `INV-${date.getFullYear()}${String(date.getMonth() + 1).padStart(2, '0')}-${String(count + 1).padStart(5, '0')}`;
  }
  next();
});

module.exports = mongoose.model('PlatformInvoice', platformInvoiceSchema);
